music.setVolume(90)
music.setTempo(76)
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(622, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Half))
music.playTone(466, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Sixteenth))
music.playTone(698, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(622, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(831, music.beat(BeatFraction.Half))
music.playTone(622, music.beat(BeatFraction.Whole))
music.playTone(554, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(622, music.beat(BeatFraction.Whole))
music.playTone(622, music.beat(BeatFraction.Half))
music.playTone(698, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(554, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.playTone(622, music.beat(BeatFraction.Half))
music.playTone(740, music.beat(BeatFraction.Whole))
music.playTone(698, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Half))
music.playTone(466, music.beat(BeatFraction.Whole))
